import { z } from "zod";

// Form Schema
export const LoginFormSchema = z.object({
  username: z.string({
    message: "Password is required",
  }),
  password: z.string().min(1, {
    message: "Password is required",
  })
});
export const BookingFieldSchema = z.object({
  type_id: z.string().nullable(),
  book_no: z.string().nullable(),
  book_date: z.string().nullable(),
  customer_no: z.string().nullable(),
  schedule_check_in_date: z.string().nullable(),
  schedule_check_out_date: z.string().nullable(),
  check_in_date: z.string().nullable(),
  check_out_date: z.string().nullable(),
  duration: z.string().nullable(),
  notes: z.string().nullable(),
  product_no: z.string().nullable(),
  bill_no: z.string().nullable(),
  create_by: z.string().nullable(),
  status: z.string().nullable(),
  lock: z.boolean().nullable(),
  org_no: z.string().nullable(),
  branch_no: z.string().nullable(),
  unit_qty: z.string().nullable(),
  subtotal: z.string().nullable(),
  discount: z.string().nullable(),
  promo_id: z.string().nullable(),
  tax: z.string().nullable(),
  tax_id: z.string().nullable(),
  total: z.string().nullable(),
  ref_no: z.string().nullable(),
  captain_no: z.string().nullable(),
  customer_service_no: z.string().nullable(),
  penalty: z.string().nullable(),
  numbers: z.array(z.any()),
  riders: z.array(z.any()),
  payments: z.array(
    z.object({
      id: z.string().nullable(),
      payment_no: z.string().nullable(),
      book_no: z.string().nullable(),
      payment_date: z.string().nullable(),
      method_id: z.string().nullable(),
      amount: z.string(),
      promo_id: z.string().nullable(),
      round: z.string().nullable(),
      discount: z.string().nullable(),
      total: z.string().nullable(),
      org_no: z.string().nullable(),
      payment_type: z.string().nullable(),
      note: z.string().nullable(),
      cash_id: z.string().nullable(),
      promo: z.array(z.any())
    })
  )
});
export const CustomerFieldSchema = z.object({
  id: z.optional(z.string().nullable()),
  customer_no: z.string().nullable(),
  name: z.string(),
  address: z.string().nullable(),
  phone: z.string().nullable(),
  email: z.string().nullable(),
  identity_number: z.string().nullable(),
  vat: z.string().nullable(),
  rating: z.string().nullable(),
  birthday: z.any().nullable(),
  age: z.string().nullable(),
  org_no: z.string().nullable(),
  type: z.string().nullable(),
  from: z.optional(z.string().nullable()),
  rider_type: z.string().nullable()
})

// api response Schema
export const AuthSchema = z.object({
  token: z.string(),
  kong: z.object({
    rsa_public_key: z.string().nullable(),
    tags: z.string().nullable(),
    id: z.string(),
    algorithm: z.string(),
    created_at: z.number().nullable(),
    secret: z.string(),
    key: z.string(),
    consumer: z.object({ id: z.string() })
  })
})
export const UserTokenSchema = z.object({
  id: z.string(),
  name: z.string(),
  username: z.string().nullable(),
  email: z.string(),
  org_no: z.string().nullable(),
  type: z.string().nullable(),
  avatar: z.optional(z.string().nullable()),
  greetings: z.string().nullable(),
  role: z.array(z.string()).nullable(),
  permission: z.any().nullable(),
  customer_no: z.string().nullable(),
  customer: z.any(),
  customers: z.any(),
  token: z.optional(z.any()),
  pending_payment: z.optional(z.array(z.any())),
});

export const ProductSchema = z.object({
  id: z.string(),
  product_no: z.string(),
  product_name: z.string(),
  product_description: z.string().nullable(),
  product_about: z.string().nullable(),
  type_id: z.string(),
  type: z.string().nullable(),
  category_id: z.string(),
  category: z.string(),
  active: z.boolean(),
  is_serial_number: z.boolean(),
  costing_method: z.string().nullable(),
  costing_evaluation: z.string().nullable(),
  uom_id: z.string().nullable(),
  uom: z.string(),
  org_no: z.string(),
  branch_no: z.string().nullable(),
  is_variant: z.boolean(),
  can_be_sold: z.boolean(),
  cogs: z.boolean(),
  multiple_uom: z.boolean(),
  is_asset: z.boolean(),
  duration_trip: z.string().nullable(),
  price: z.string(),
  variant: z.string().nullable(),
  location_id: z.string().nullable(),
  location: z.string().nullable(),
  uoms: z.array(z.any()),
  variants: z.array(z.object({
    id: z.string(),
    variant_name: z.string(),
    product_no: z.string(),
    product_sku: z.string().nullable(),
    notes: z.string().nullable(),
    org_no: z.string(),
    active: z.boolean(),
    total_rider: z.number().nullable(),
    created_at: z.string().nullable(),
    updated_at: z.string().nullable(),
    branch_no: z.string().nullable(),
  })),
  amenities: z.any(),
  pictures: z.array(z.any())
});

export const SingleProductSchema = z.object({
  id: z.string(),
  product_no: z.string(),
  product_name: z.string(),
  product_description: z.string().nullable(),
  product_about: z.string().nullable(),
  type_id: z.string(),
  category_id: z.string(),
  active: z.boolean(),
  is_serial_number: z.boolean(),
  costing_method: z.string().nullable(),
  costing_evaluation: z.string().nullable(),
  uom_id: z.string().nullable(),
  org_no: z.string().nullable(),
  branch_no: z.string().nullable(),
  prices: z.array(
    z.object({
      id: z.string(),
      product_no: z.string(),
      product_sku: z.string().nullable(),
      price_date: z.string(),
      uom_id: z.string().nullable(),
      amount: z.string(),
      notes: z.string().nullable()
    })),
  is_variant: z.boolean(),
  is_guided: z.boolean(),
  can_be_sold: z.boolean(),
  cogs: z.boolean(),
  multiple_uom: z.boolean(),
  is_asset: z.boolean(),
  duration_trip: z.string().nullable(),
  location_id: z.string().nullable(),
  location: z.string().nullable(),
  routes: z.array(
    z.object({
      id: z.string(),
      name: z.string(),
      longitude: z.string().nullable(),
      latitude: z.string().nullable(),
      org_no: z.string().nullable(),
      branch_no: z.string().nullable(),
    })
  ),
  sell_price: z.string(),
  sell_date: z.string().nullable(),
  uoms: z.array(z.any()),
  variants: z.array(
    z.object({
      id: z.string().nullable(),
      variant_name: z.string().nullable(),
      product_sku: z.string().nullable(),
      notes: z.string().nullable(),
      org_no: z.string().nullable(),
      active: z.boolean(),
      price: z.string().nullable(),
      prices: z.array(
        z.object({
          id: z.string(),
          product_no: z.string(),
          product_sku: z.string().nullable(),
          price_date: z.string(),
          uom_id: z.string().nullable(),
          amount: z.string().nullable(),
          notes: z.string().nullable(),
          active: z.boolean(),
          created_at: z.string().nullable(),
          updated_at: z.string().nullable()
        })
      ).nullable()
    }),
  ),
  addons: z.array(z.any()),
  amenities: z.any(),
  pictures: z.array(
    z.object({
      id: z.string(),
      product_no: z.string(),
      filename: z.string(),
      mime_type: z.string(),
      extension: z.string(),
      type: z.string(),
      size: z.string(),
      disk: z.string(),
      org_no: z.string(),
      branch_no: z.string().nullable(),
      url: z.string()
    })
  )
});
export const CustomerSchema = z.object({
  id: z.string(),
  customer_no: z.string(),
  name: z.string(),
  address: z.string().nullable(),
  phone: z.string().nullable(),
  email: z.string().nullable(),
  identity_number: z.string().nullable(),
  vat: z.string().nullable(),
  rating: z.string().nullable(),
  birthday: z.string().nullable(),
  age: z.string().nullable(),
  org_no: z.string().nullable(),
  type: z.string().nullable(),
})
export const BookingSchema = z.array(
  z.object({
    id: z.string().nullable(),
    type_id: z.string().nullable(),
    book_no: z.string().nullable(),
    book_no_short: z.string().nullable(),
    book_date: z.string().nullable(),
    customer_no: z.string().nullable(),
    customer: z.string().nullable(),
    customer_address: z.string().nullable(),
    customer_phone: z.string().nullable(),
    customer_email: z.string().nullable(),
    customer_identity_number: z.string().nullable(),
    customer_vat: z.string().nullable(),
    customer_org_no: z.string().nullable(),
    customer_branch_no: z.string().nullable(),
    customer_rating: z.string().nullable(),
    customer_type: z.string().nullable(),
    customer_birthday: z.string().nullable(),
    customer_age: z.string().nullable(),
    schedule_check_in_date: z.string().nullable(),
    schedule_check_out_date: z.string().nullable(),
    check_in_date: z.string().nullable(),
    check_out_date: z.string().nullable(),
    duration: z.string().nullable(),
    notes: z.string().nullable(),
    product_no: z.string().nullable(),
    bill_no: z.string().nullable(),
    create_by: z.string().nullable(),
    status: z.string().nullable(),
    lock: z.boolean().nullable(),
    org_no: z.string().nullable(),
    unit_qty: z.string().nullable(),
    subtotal: z.string().nullable(),
    discount: z.string().nullable(),
    promo_id: z.string().nullable(),
    tax: z.string().nullable(),
    tax_id: z.string().nullable(),
    total: z.string().nullable(),
    penalty: z.string().nullable(),
    total_dp: z.number().nullable(),
    total_payment: z.number().nullable(),
    total_refund: z.number().nullable(),
    ref_no: z.string().nullable(),
    captain_no: z.string().nullable(),
    captains: z.array(z.any()),
    customer_service_no: z.any(),
    numbers: z.array(z.any()),
    on_the_spot: z.boolean()
  })
)
export const SingleBookingSchema = z.object({
  id: z.string(),
  type_id: z.string().nullable(),
  book_date: z.string().nullable(),
  book_no: z.string().nullable(),
  book_no_short: z.string().nullable(),
  waiver_no: z.string().nullable(),
  waiver_no_short: z.string().nullable(),
  customer_no: z.string().nullable(),
  schedule_check_in_date: z.string().nullable(),
  schedule_check_out_date: z.string().nullable(),
  check_in_date: z.string().nullable(),
  check_out_date: z.string().nullable(),
  duration: z.string().nullable(),
  notes: z.string().nullable(),
  product_no: z.string().nullable(),
  bill_no: z.string().nullable(),
  create_by: z.string().nullable(),
  org_no: z.string().nullable(),
  branch_no: z.string().nullable(),
  unit_qty: z.string().nullable(),
  subtotal: z.string().nullable(),
  discount: z.string().nullable(),
  promo_id: z.string().nullable(),
  tax: z.string().nullable(),
  tax_id: z.string().nullable(),
  total: z.string().nullable(),
  status: z.string().nullable(),
  lock: z.boolean().nullable(),
  ref_no: z.string().nullable(),
  ref_date: z.string().nullable(),
  captain_no: z.string().nullable(),
  customer_service_no: z.string().nullable(),
  penalty: z.string().nullable(),
  units: z.array(z.any()),
  numbers: z.array(z.any()),
  payment_dp: z.record(z.any()),
  payment: z.array(z.any()),
  customer: z.record(z.any()),
  refunds: z.array(z.any()),
  requests: z.array(z.any()),
  riders: z.array(z.any())
}) 
export const BookByCustomerSchema = z.array(
  z.object({
    id: z.string(),
    type: z.string().nullable(),
    type_id: z.string().nullable(),
    book_no: z.string(),
    ref_no: z.string().nullable(),
    book_date: z.string().nullable(),
    customer_no: z.string().nullable(),
    schedule_check_in_date: z.string().nullable(),
    schedule_check_out_date: z.string().nullable(),
    check_in_date: z.string().nullable(),
    check_out_date: z.string().nullable(),
    duration: z.string().nullable(),
    notes: z.string().nullable(),
    product_no: z.string().nullable(),
    bill_no: z.string().nullable(),
    create_by: z.string().nullable(),
    status: z.string().nullable(),
    lock: z.boolean().nullable(),
    org_no: z.string().nullable(),
    unit_qty: z.string().nullable(),
    subtotal: z.string().nullable(),
    discount: z.string().nullable(),
    tax: z.string().nullable(),
    tax_id: z.string().nullable(),
    total: z.string().nullable(),
    penalty: z.string().nullable(),
    payment_dp: z.number().nullable(),
    payment_amount: z.number().nullable(),
    payments: z.array(z.any()),
    units: z.array(z.any()),
    numbers: z.array(z.any()),
    downPayments: z.array(z.any()),
    customer: z.object({
      id: z.string(),
      customer_no: z.string().nullable(),
      name: z.string().nullable(),
      address: z.string().nullable(),
      phone: z.string().nullable(),
      email: z.string().nullable(),
      identity_number: z.string().nullable(),
      vat: z.string().nullable(),
      org_no: z.string().nullable(),
      branch_no: z.string().nullable(),
      rating: z.string().nullable(),
      type: z.string().nullable(),
      birthday: z.string().nullable(),
      age: z.string().nullable()
    }),
    refunds: z.array(z.any()),
    requests: z.array(z.any()),
    riders: z.array(z.any())
  })
)
export const InvoiceByCustomerSchema = z.array(
  z.object({
    id: z.string(),
    type: z.string().nullable(),
    type_id: z.string().nullable(),
    invoice_no: z.string(),
    book_no: z.string().nullable(),
    book_date: z.string().nullable(),
    customer_no: z.string().nullable(),
    schedule_check_in_date: z.string().nullable(),
    schedule_check_out_date: z.string().nullable(),
    check_in_date: z.string().nullable(),
    check_out_date: z.string().nullable(),
    duration: z.string().nullable(),
    notes: z.string().nullable(),
    product_no: z.string().nullable(),
    bill_no: z.string().nullable(),
    create_by: z.string().nullable(),
    status: z.string().nullable(),
    lock: z.boolean().nullable(),
    org_no: z.string().nullable(),
    branch_no: z.string().nullable(),
    unit_qty: z.string().nullable(),
    subtotal: z.string().nullable(),
    discount: z.string().nullable(),
    tax: z.string().nullable(),
    tax_id: z.string().nullable(),
    total: z.string().nullable(),
    penalty: z.string().nullable(),
    payment_dp: z.number().nullable(),
    payment_amount: z.number().nullable(),
    payments: z.array(z.any()),
    units: z.array(z.any()),
    numbers: z.array(z.any()),
    downPayments: z.array(z.any()),
    customer: z.object({
      id: z.string(),
      customer_no: z.string().nullable(),
      name: z.string().nullable(),
      address: z.string().nullable(),
      phone: z.string().nullable(),
      email: z.string().nullable(),
      identity_number: z.string().nullable(),
      vat: z.string().nullable(),
      org_no: z.string().nullable(),
      branch_no: z.string().nullable(),
      rating: z.string().nullable(),
      type: z.string().nullable(),
      birthday: z.string().nullable(),
      age: z.string().nullable()
    }),
    refunds: z.array(z.any()),
    requests: z.array(z.any()),
    riders: z.array(z.any())
  })
)
export const branchSchema = z.array(
  z.object({
    branch_no: z.string().nullable(),
    org_no: z.string().nullable(),
    alias: z.string().nullable(),
    name: z.string().nullable(),
    second_name: z.string().nullable(),
    address: z.string().nullable(),
    phone: z.string().nullable(),
    email: z.string().nullable(),
    api_id: z.string().nullable(),
    ref_no: z.string().nullable(),
    note: z.string().nullable(),
    pic: z.string().nullable(),
  })
)