import React from 'react';
import { Metadata } from 'next';
import Container from '@/components/ui/container';
import { ChevronLeft } from 'lucide-react';
import { Card, CardContent, CardHeader, CardFooter, CardTitle } from '@/components/ui/card';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Star, Clock, MapPin } from 'lucide-react';
import { Button } from '@/components/ui/button/button';
import OpenModalButton from '@/components/ui/button/open-modal-button';

export const metadata: Metadata = {
  title: 'Trips',
  description: 'Generated by create next app'
}

function Trips() {
  return (
    <div className="flex flex-col min-h-screen">
      <Tabs defaultValue='on-progress'>
        <Container className="py-6 sticky top-0 z-30 bg-background w-full flex justify-between items-center shrink-0">
          <button type="button">
            <ChevronLeft className="w-5 h-5" />
          </button>
          <h3 className="font-bold text-sm text-foreground/75">Trips</h3>
          <div></div>
        </Container>
        <Container el="nav" className="sticky top-0 z-30 bg-background pb-3 pt-1 border-b shadow-sm rounded-3xl">
          <TabsList className="flex gap-6 justify-start bg-background text-foreground/50">
            <TabsTrigger value='on-progress' className="font-bold">On Progress</TabsTrigger>
            <TabsTrigger value='history' className="font-bold">History</TabsTrigger>
          </TabsList>
        </Container>
        <div className="relative mt-6 mb-20">
          <TabsContent value='on-progress'>
            <Container className="space-y-6">
              <Card className="shadow-md">
                <CardHeader className="flex-row items-center justify-between">
                  <CardTitle className="text-foreground/75">Beginner Ride</CardTitle>
                  <div className="flex items-center text-foreground/50 gap-x-2 !mt-0">
                    <Star className="w-4 h-4" fill="#F6891F" strokeWidth={0} />
                    <p className="inline-block text-xs font-normal">4.9 (120 reviews)</p>
                  </div>
                </CardHeader>
                <CardContent className="space-y-0.5">
                  <div className="flex items-center justify-between">
                    <div className="text-foreground/50">
                      <span className="text-sm font-normal">#FEJR - 17 Agustus 2024</span>
                    </div>
                    <div className="flex items-center text-foreground/50 gap-x-2">
                      <span className="text-xs font-normal">45 minutes</span>
                      <Clock className="text-brand inline-block w-4 h-4" />
                    </div>
                  </div>
                  <div className="flex items-center justify-between">
                    <div className="text-foreground/50">
                      <span className="text-sm  uppercase text-brand font-normal">On Schedule</span>
                    </div>
                    <div className="flex items-center text-foreground/50 gap-x-2">
                      <span className="text-xs font-normal">Marina</span>
                      <MapPin className="text-brand inline-block w-4 h-4" />
                    </div>
                  </div>
                </CardContent>
              </Card>
              <Card className="shadow-md">
                <CardHeader className="flex-row items-center justify-between">
                  <CardTitle className="text-foreground/75">Magrove Morosari</CardTitle>
                  <div className="flex items-center text-foreground/50 gap-x-2 !mt-0">
                    <Star className="w-4 h-4" fill="#F6891F" strokeWidth={0} />
                    <p className="inline-block text-xs font-normal">4.9 (120 reviews)</p>
                  </div>
                </CardHeader>
                <CardContent className="space-y-0.5">
                  <div className="flex items-center justify-between">
                    <div className="text-foreground/50">
                      <span className="text-sm font-normal">#FEJR - 17 Agustus 2024</span>
                    </div>
                    <div className="flex items-center text-foreground/50 gap-x-2">
                      <span className="text-xs font-normal">45 minutes</span>
                      <Clock className="text-brand inline-block w-4 h-4" />
                    </div>
                  </div>
                  <div className="flex items-center justify-between">
                    <div className="text-foreground/50">
                      <span className="text-sm  uppercase text-green-500 font-normal">Finish</span>
                    </div>
                    <div className="flex items-center text-foreground/50 gap-x-2">
                      <span className="text-xs font-normal">Marina</span>
                      <MapPin className="text-brand inline-block w-4 h-4" />
                    </div>
                  </div>
                </CardContent>
                <CardFooter className="grid grid-cols-2 w-full gap-3">
                  <Button variant="secondary" className="text-xs h-auto">Re-Book</Button>
                  {/* <Button className="bg-brand text-xs h-auto hover:bg-brand/90">Write Reviews</Button> */}
                  <OpenModalButton
                    view='review-view'
                    variant='default'
                  >
                    Write Reviews
                  </OpenModalButton>
                </CardFooter>
              </Card>
              <Card className="shadow-md">
                <CardHeader className="flex-row items-center justify-between">
                  <CardTitle className="text-foreground/75">Fun Ride</CardTitle>
                  <div className="flex items-center text-foreground/50 gap-x-2 !mt-0">
                    <Star className="w-4 h-4" fill="#F6891F" strokeWidth={0} />
                    <p className="inline-block text-xs font-normal">4.9 (120 reviews)</p>
                  </div>
                </CardHeader>
                <CardContent className="space-y-0.5">
                  <div className="flex items-center justify-between">
                    <div className="text-foreground/50">
                      <span className="text-sm font-normal">#FEJR - 17 Agustus 2024</span>
                    </div>
                    <div className="flex items-center text-foreground/50 gap-x-2">
                      <span className="text-xs font-normal">45 minutes</span>
                      <Clock className="text-brand inline-block w-4 h-4" />
                    </div>
                  </div>
                  <div className="flex items-center justify-between">
                    <div className="text-foreground/50">
                      <span className="text-sm  uppercase text-green-500 font-normal">Finish</span>
                    </div>
                    <div className="flex items-center text-foreground/50 gap-x-2">
                      <span className="text-xs font-normal">Marina</span>
                      <MapPin className="text-brand inline-block w-4 h-4" />
                    </div>
                  </div>
                </CardContent>
                <CardFooter className="grid grid-cols-2 w-full gap-3">
                  <Button variant="secondary" className="text-xs h-auto">Re-Book</Button>
                  {/* <Button className="bg-brand text-xs h-auto hover:bg-brand/90">Write Reviews</Button> */}
                  <OpenModalButton
                    view='rider-detail-view'
                    variant='default'
                  >
                    Write Reviews
                  </OpenModalButton>
                </CardFooter>
              </Card>
            </Container>
          </TabsContent>
          <TabsContent value='history'>
            testing
          </TabsContent>
        </div>
      </Tabs>
    </div>
  )
}

export default Trips;