import React from 'react';
import { Metadata } from 'next';
import Container from '@/components/ui/container';
import Image from 'next/image';
import { Input } from '@/components/ui/input';
import { Search } from 'lucide-react';
import { Tabs, TabsContent } from '@/components/ui/tabs';
import { Card } from '@/components/ui/card';
import Link from 'next/link';
import { MapPin } from 'lucide-react';

export const metadata: Metadata = {
  title: 'Explore',
  description: 'Generated by create next app'
}

function Explore() {
  return (
    <div className="flex flex-col min-h-screen">
        <Container className="mt-6 mb-4 space-y-4">
          <div className="flex items-center justify-start gap-x-2">
            <Image
              src="/images/avatar.png"
              alt="avatar"
              width={34}
              height={34}
              className="object-contain"
            />
            <p className="text-sm">Hi, Dimas Amrullah</p>
          </div>
          <div className="relative">
            <Search className="absolute w-6 h-6 top-1/2 left-2 transform -translate-y-1/2" />
            <Input
              type="text"
              placeholder="Where do yo want to go"
              className="rounded-full pl-12"
            />
          </div>
        </Container>
        <Container el="nav" className="sticky top-0 z-30 bg-background pb-3 pt-1 border-b shadow-sm rounded-3xl">
          <ul className="flex gap-6">
            <li className="relative flex items-center g-animate py-3">
              <button type="button" className="text-sm font-semibold text-foreground/50 hover:text-brand">Trip</button>
            </li>
            <li className="relative flex items-center g-animate py-3">
              <button type="button" className="text-sm font-semibold text-foreground/50 hover:text-brand">Coastal</button>
            </li>
            <li className="relative flex items-center g-animate py-3">
              <button type="button" className="text-sm font-semibold text-foreground/50 hover:text-brand">Rental</button>
            </li>
          </ul>
        </Container>
      <div className="relative mt-6 mb-20">
        <Tabs defaultValue='trip'>
          <TabsContent value='trip'>
            <Card className="border-none shadow-none py-2">
              <Container className="relative flex flex-col">
                <div className="relative flex-shrink-0 rounded-md overflow-hidden group">
                  <Link href={`/d`}>
                    <div className="flex aspect-w-5 aspect-h-4 w-full h-0">
                      <Image
                        src="/images/img-grid-3.png"
                        alt="image"
                        width={0}
                        height={0}
                        sizes="100vw"
                        className="h-full w-full object-cover transition-all duration-300 group-hover:scale-105"
                      />
                    </div>
                  </Link>
                </div>
                <div className="space-y-0.5 mt-3">
                  <div>
                    <div className="flex justify-between items-center">
                      <Link
                        href={`/d`}
                        className="truncate mr-8"
                      >
                        <h4 className="text-base font-semibold text-brand truncate">
                          Beginer Ride
                        </h4>
                      </Link>
                      <div className="flex items-center text-xs font-normal text-foreground/50">
                        <span className="mr-1">Marina</span>
                        <MapPin className="inline-block text-brand w-4 h-4" />
                      </div>
                    </div>
                    <p className="text-xs text-foreground/50 font-normal truncate">Lorem ipsum dolor sit amet.</p>
                  </div>

                  <div className="flex items-center text-foreground/50">
                    <p className="text-base font-medium">
                      Rp 1.000.000
                    </p>
                    <span className="text-xs">/single</span>
                  </div>
                </div>
              </Container>
            </Card>
            <Card className="border-none shadow-none py-2">
              <Container className="relative flex flex-col">
                <div className="relative flex-shrink-0 rounded-md overflow-hidden z-1 group">
                  <Link href={`/d`}>
                    <div className="flex aspect-w-5 aspect-h-4 w-full h-0">
                      <Image
                        src="/images/img-grid-1.png"
                        alt="image"
                        width={0}
                        height={0}
                        sizes="100vw"
                        className="h-full w-full object-cover transition-all duration-300 group-hover:scale-105"
                      />
                    </div>
                  </Link>
                </div>
                <div className="space-y-0.5 mt-3">
                  <div>
                    <div className="flex justify-between items-center">
                      <Link
                        href={`/d`}
                        className="truncate mr-8"
                      >
                        <h2 className="text-base font-semibold text-brand truncate">
                          Beginer Ride
                        </h2>
                      </Link>
                      <div className="flex items-center text-xs font-normal text-foreground/50">
                        <span className="mr-1">Marina</span>
                        <MapPin className="inline-block text-brand w-4 h-4" />
                      </div>
                    </div>
                    <p className="text-xs text-foreground/50 font-normal truncate">Lorem ipsum dolor sit amet.</p>
                  </div>

                  <div className="flex items-center text-foreground/50">
                    <p className="text-base text-foreground/75 font-medium">
                      Rp 1.000.000
                    </p>
                    <span className="text-xs">/single</span>
                  </div>
                </div>
              </Container>
            </Card>
          </TabsContent>
          <TabsContent value='coastal'>
            testing 2
          </TabsContent>
          <TabsContent value='rental'>
            testing
          </TabsContent>
        </Tabs>
      </div>
    </div>
  )
}

export default Explore;