import React from 'react';
import { Metadata } from 'next';
import ConfirmNPayClient from './module/confirm-n-pay-client';

export const metadata: Metadata = {
  title: 'Confirm & Pay',
  description: 'Generated by create next app'
}

function ConfirmNPay() {
  return (
    <ConfirmNPayClient />
  );
}

export default ConfirmNPay;
