
import React from 'react';
import { Metadata } from 'next';
import { getSession } from '@/lib/session';
import ConfirmNPayClient from './module/confirm-n-pay-client';

export const metadata: Metadata = {
  title: 'Confirm & Pay',
  description: 'Generated by create next app'
}

async function ConfirmNPay() {
  const session = await getSession();
  let user;
  if(session) {
    user = session.user;
  }
  return <ConfirmNPayClient user={user}  />;
}

export default ConfirmNPay;
