import React from 'react';
import { Metadata, ResolvingMetadata } from 'next';
import Container from '@/components/ui/container';
import { MapPin, Clock, Star, Check, Camera, CupSoda, Bath, ChevronLeft, Share2, Divide } from 'lucide-react';
import { Card, CardContent } from '@/components/ui/card';
import HeaaderDetailCarousel from '@/components/partial/header/header-detail-carousel';
import OpenModalButton from '@/components/ui/button/open-modal-button';
import Heading from '@/components/ui/heading';
import { Button } from '@/components/ui/button/button';
import Link from 'next/link';
import { getSingleProductPublic, getAllProductPublic } from '@/lib/data';
import { msToTime, secondsToTime } from '@/lib/helper';
import { SingleProductSchema } from '@/lib/schema';
import { z } from 'zod';
import { Suspense } from 'react';
import { ReserveButtonLoader, ProductDetailContentLoader } from '@/components/partial/loader';
import ReserveButton from './module/reserve-button';
import AboutDetailModal from './module/about-detail-modal';
import ShareButton from './module/share-button';
import Icon from '@/components/ui/icon';

type Props = {
  params: { slug: string }
  searchParams?: { [key: string]: string | string[] | undefined }
}

export async function generateMetadata(
  { params, searchParams }: Props,
  parent: ResolvingMetadata
): Promise<Metadata> {
  const prodArr = await getAllProductPublic();
  const selectedProd = prodArr.find(product => product.slug === params.slug);

  if (!selectedProd) {
    throw new Error("Product not found")
  }
  const product = await getSingleProductPublic(selectedProd.id);

  return {
    title: product.product_name,
    description: 'Generated by create next app'
  }
}

async function Detail({
  params,
}: Props) {
  const prodArr = await getAllProductPublic();
  const selectedProd = prodArr.find(product => product.slug === params.slug);
  if (!selectedProd) {
    return (
      <div>Product not found</div>
    )
  }
  const product = await getSingleProductPublic(selectedProd.id);
  console.log(product)
  const validTripDuration = product.duration_trip !== null ? product.duration_trip : '0';
  return (
    <React.Fragment>
      <div className="flex flex-col min-h-screen">
        <div className="relative">
          <HeaaderDetailCarousel pictures={selectedProd.pictures} />
          <div className="absolute z-30 top-6 left-0 right-0 px-[30px] flex items-center justify-between">
            <Button
              type='button'
              variant="outline"
              size="icon"
              className="bg-background/50 rounded-full h-7 w-7 p-1"
            >
              <Link href="/explore">
                <ChevronLeft className="w-5 h-5 text-muted-foreground" />
              </Link>
            </Button>
            <ShareButton />
          </div>
        </div>
        <div className="flex-1 w-full py-7 mb-20">
          <Suspense fallback={<ProductDetailContentLoader />}>
            <Container className="flex items-center justify-between">
              <Heading variant='base' className="text-brand truncate mr-4">{product.product_name}</Heading>
              <div className="flex items-center text-xs font-normal text-foreground/50">
                <span className="mr-1">{product.location}</span>
                <MapPin className="inline-block text-brand w-4 h-4" />
              </div>
            </Container>
            <Container>
              <Card className="my-4">
                <CardContent className="p-3 flex items-center justify-between">
                  <div className="flex items-center text-foreground/50 gap-x-2">
                    <Clock className="inline-block w-5 h-5" />
                    <span className="font-normal text-xs">Duration {secondsToTime(parseInt(validTripDuration))} Hours</span>
                  </div>
                  <div className="flex justify-center items-center text-foreground/50 gap-x-2">
                    <Star className="w-4 h-4" fill="#F6891F" strokeWidth={0} />
                    <p className="inline-block text-xs font-normal">{product.rating} (0 reviews)</p>
                  </div>
                </CardContent>
              </Card>
            </Container>
            <Container className="mt-1">
              <dl className="space-y-4">
                <div className="flex items-start gap-x-6 gap-y-4">
                  <dt className="text-sm font-medium text-foreground/50">
                    <Check className="w-5 h-5" />
                  </dt>
                  <dd className="text-foreground/75 mt-0 pt-0">
                    <h3 className="text-sm font-normal tracking-tight">Self Riding</h3>
                    <p className="text-xs text-foreground/50">You can ride your own Jetsky</p>
                  </dd>
                </div>
                <div className="flex items-start gap-x-6 gap-y-4">
                  <dt className="text-sm font-medium text-foreground/50">
                    <Check className="w-5 h-5" />
                  </dt>
                  <dd className="text-foreground/75 mt-0 pt-0">
                    <h3 className="text-sm font-normal tracking-tight">Captain Companion</h3>
                    <p className="text-xs text-foreground/50">You trip guided by our captain</p>
                  </dd>
                </div>
              </dl>
            </Container>
            <Container className="flex flex-col w-full mx-auto mt-5">
              <h3 className="font-bold text-sm text-foreground/75 mb-3">Amenities</h3>
              <dl className="space-y-4">
                {product.amenities.map((pa: any) => {
                  return (
                    <React.Fragment key={pa.id}>
                      <div className="flex items-start gap-x-6 gap-y-4">
                        <dt className="text-sm font-medium text-foreground/50">
                          {/* <CupSoda className="w-5 h-5" /> */}
                          <Icon name={pa.icon} className="w-5 h-5"/>
                        </dt>
                        <dd className="text-foreground/75 mt-0 pt-0">
                          <h3 className="text-sm font-normal tracking-tight">{pa.amenity}</h3>
                          {/* <p className="text-xs text-foreground/50">
                            Kita sudah menyediakan Handuk, Sampo, Sabun dan Sunblock jika diperlukan
                          </p> */}
                        </dd>
                      </div>

                    </React.Fragment>
                  )
                })}
                {/* <div className="flex items-start gap-x-6 gap-y-4">
                <dt className="text-sm font-medium text-foreground/50">
                  <Camera className="w-5 h-5" />
                </dt>
                <dd className="text-foreground/75 mt-0 pt-0">
                  <h3 className="text-sm font-normal tracking-tight">Documentation Include</h3>
                  <p className="text-xs text-foreground/50">Kita sudah menyediakan Handuk, Sampo, Sabun dan Sunblock
                    jika diperlukan </p>
                </dd>
              </div>
              <div className="flex items-start gap-x-6 gap-y-4">
                <dt className="text-sm font-medium text-foreground/50">
                  <Bath className="w-5 h-5" />
                </dt>
                <dd className="text-foreground/75 mt-0 pt-0">
                  <h3 className="text-sm font-normal tracking-tight">Bathroom Essential Provided</h3>
                  <p className="text-xs text-foreground/50">Kita sudah menyediakan Handuk, Sampo, Sabun dan Sunblock
                    jika diperlukan </p>
                </dd>
              </div>
              <div className="flex items-start gap-x-6 gap-y-4">
                <dt className="text-sm font-medium text-foreground/50">
                  <CupSoda className="w-5 h-5" />
                </dt>
                <dd className="text-foreground/75 mt-0 pt-0">
                  <h3 className="text-sm font-normal tracking-tight">Snack & Mineral Water</h3>
                  <p className="text-xs text-foreground/50">Tersedia snack dan mineral water untuk setiap 1 unit jetski</p>
                </dd>
              </div> */}
              </dl>
            </Container>
            <Container el="article" className="flex flex-col mx-auto mt-5">
              <h3 className="font-bold text-sm text-foreground/75 mb-3">About</h3>
              <div className="text-foreground/50 font-normal text-xs">
                <p className="">
                  {product.product_description}
                </p>
              </div>
              <div className="bg-background mt-6">
                <h3 className="font-semibold text-sm text-foreground/75">Riding Route</h3>
                <div className="mt-2">
                  <ol className="relative text-gray-500 ms-2 border-s-2 border-dashed border-muted-foreground">
                    {product.routes.map((route: any) => (
                      <li key={route.id} className="mb-5 ms-6">
                        <span className="absolute flex items-center justify-center w-4 h-4 border-2 border-muted-foreground bg-background rounded-full -start-2 ring-2 ring-background" />
                        <p className="text-xs tracking-tight">{route.name}</p>
                      </li>
                    ))}
                  </ol>
                </div>
              </div>
            </Container>
          </Suspense>
        </div>
      </div>
      <Suspense fallback={<ReserveButtonLoader />}>
        <ReserveButton product={product} />
      </Suspense>
      <AboutDetailModal data={product.routes} />
    </React.Fragment>
  )
}

export default Detail;