import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { cn } from "@/assets/styles/utils";
import { fontSans } from "@/assets/styles/fonts";
import ManagedModal from "@/components/ui/modal/managed-modal";

import "@/assets/styles/globals.css";
// import "@/assets/styles/toggle-group.css"

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: {
    template: ' %s | Booking Safari',
    default: 'BRP Commerce',
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={cn(
        'bg-neutral-100 min-h-screen font-sans antialised',
        fontSans.variable
      )}>
        <main className="wrapper bg-background flex flex-col justify-between w-full h-full min-h-screen">
          {/* header here */}
          {children}
          {/* foooter here */}
          <ManagedModal />
        </main>
      </body>
    </html>
  );
}
