import React from "react";
import { Metadata } from "next";
import HomePage from "./homepage-client";

export const metadata: Metadata = {
  title: 'Home | Booking Safari',
  description: 'Generated by create next app',
};

function Home() {
  return <HomePage />
}

export default Home;
