import React from 'react';
import { Metadata } from 'next';
import Container from '@/components/ui/container';
import Link from 'next/link';
import Image from 'next/image';
import { ChevronLeft, Star } from 'lucide-react';
import { Button } from '@/components/ui/button/button';
import Heading from '@/components/ui/heading';
import RatingForm from './module/rating-form';
import { getAllProductPublic, getBooking, getInvoiceByCustomer } from '@/lib/data';
import { getSession } from '@/lib/session';
import { currency } from '@/lib/helper';
import { Ratings } from '@/components/ui/ratings';
import TopTitle from './module/top-title';

export const metadata: Metadata = {
  title: 'Invoice',
  description: 'Generated by create next app'
}

async function InvoiceDetail({
  params,
}: {
  params: { noShort: string };
}) {
  const session = await getSession();
  // @ts-ignore
  const { token, customer_no } = session.user;
  const invoiceBody = {
    customer_no: customer_no as string,
    type: "invoice",
    begin: null,
    end: null
  }
  const invoices = await getInvoiceByCustomer(token, invoiceBody);
  const invoice = invoices.find(inv => inv.invoice_no.split('/').pop() === params.noShort);
  const numbers = invoice?.numbers.filter((number: any) => number.qty !== '0');

  const products = await getAllProductPublic();
  let booking = null;
  if (invoice) {
    booking = await getBooking(token, invoice.id);
  }

  const totalPrice = invoice?.numbers.reduce((acc, val) => {
    return acc + parseInt(val.price.replace(/\./g, '')) * parseInt(val.qty);
  }, 0);

  const PriceDetailComp = () => {
    return (
      <Container className="border-t-4 border-slate-100 bg-background py-8 space-y-6">
        <div>
          <h3 className="font-bold text-base text-foreground/75 mb-3">Price Details</h3>
          <dl className="space-y-4">
            {invoice?.numbers.map((number, idx) => {
              const subTotal = number.price.replace(/\./g, '') * number.qty;
              return (
                <React.Fragment key={idx}>
                  {number.qty > 0 &&
                    <div className="flex items-center justify-between gap-x-6 gap-y-4">
                      <dt className="text-sm font-medium text-foreground/50">
                        {currency(parseInt(number.price.replace(/\./g, '')))} x {number.qty} {number.variant} Ride
                      </dt>
                      <dd className="text-foreground/50 text-sm">
                        {currency(subTotal)}
                      </dd>
                    </div>
                  }
                </React.Fragment>
              )
            })}
          </dl>
        </div>
        {/* <div>
          <h3 className="font-bold text-base text-foreground/75 mb-3">Add Ons</h3>
          <dl className="space-y-4">
            <div className="flex items-center justify-between gap-x-6 gap-y-4">
              <dt className="text-sm font-medium text-foreground/50">
                Rp 000.000 x 0 Single Ride
              </dt>
              <dd className="text-foreground/50 text-sm">
                Rp 000,000
              </dd>
            </div>
          </dl>
        </div> */}
        <hr className="border border-slate-200" />
        <div>
          <dl className="space-y-4">
            <div className="flex items-center justify-between gap-x-6 gap-y-4">
              <dt className="text-sm font-semibold text-foreground/75">
                Total
              </dt>
              <dd className="text-foreground/75 font-semibold text-sm">
                {currency(totalPrice)}
              </dd>
            </div>
          </dl>
        </div>
      </Container>
    )
  }

  return (
    <div className="flex flex-col min-h-screen mb-20">
      <TopTitle label='Invoice' />
      <Container>
        {numbers?.map((invNumber: any) => {
          const productVal = products.find(p => p.product_no === invNumber.product_no);

          let ratingVal = {
            rating: null,
            rating_notes: null
          }
          if (booking) {
            const numberVal = booking.numbers.find(bn => bn.id === invNumber.id);
            ratingVal = {
              rating: numberVal.rating,
              rating_notes: numberVal.rating_notes,
            }
          }
          return (
            <React.Fragment key={invNumber.id}>
              <div className="flex items-start bg-background py-6 gap-x-6">
                <div className="w-32 flex-shrink-0 overflow-hidden rounded-md">
                  <Link href={"#"}>
                    <div className="aspect-w-6 aspect-h-4 w-full h-full">
                      <Image
                        src="/images/sea-doo.svg"
                        alt="image"
                        width={0}
                        height={0}
                        sizes="100vw"
                        className="object-cover transition-all duration-300 group-hover:scale-105"
                        priority={true}
                      />
                    </div>
                  </Link>
                </div>
                <div className="flex flex-col space-y-3 flex-grow min-w-0">
                  <div className="min-w-0">
                    <h4 className="text-base font-semibold text-foreground/75 truncate">
                      {productVal?.product_name}
                    </h4>
                    <p className="text-xs text-foreground/50 font-normal mt-1 truncate">{productVal?.product_description}</p>
                  </div>
                  <div className="flex items-center text-foreground/50 gap-x-2">
                    <Star className="w-4 h-4" fill="#F6891F" strokeWidth={0} />
                    <p className="inline-block text-xs font-normal">4.9 (120 reviews)</p>
                  </div>
                </div>
              </div>
              <RatingForm
                invoiceId={invoice?.id as string}
                numberId={invNumber.id}
                user={session?.user}
                ratingVal={ratingVal}
              />
            </React.Fragment>
          )
        })}
      </Container>
      <PriceDetailComp />
      <div className="flex items-center justify-center mt-10">
        <Button
          className="bg-brand hover:bg-brand/90"
        >Download Invoice</Button>
      </div>
    </div>
  )
}

export default InvoiceDetail;